<?php

declare(strict_types=1);

namespace Zaphyr\PluginInstaller\Operations;

use Symfony\Component\Yaml\Yaml;
use Zaphyr\PluginInstaller\Plugin;
use Zaphyr\PluginInstaller\PluginUpdate;
use Zaphyr\Utils\File;

/**
 * @author merloxx <merloxx@zaphyr.org>
 */
class PluginClassesOperator extends AbstractOperator
{
    /**
     * {@inheritdoc}
     */
    public function install(Plugin $plugin): void
    {
        $classes = $this->getExistingClasses();
        $classes = $this->addClasses($classes, $plugin->getClasses());

        $this->processConfigFile($classes);
    }

    /**
     * {@inheritdoc}
     */
    public function update(PluginUpdate $pluginUpdate): void
    {
        $currentClasses = $pluginUpdate->getCurrentPlugin()->getClasses();
        $newClasses = $pluginUpdate->getNewPlugin()->getClasses();

        $classes = $this->getExistingClasses();
        $classes = $this->removeClasses($classes, $currentClasses);
        $classes = $this->addClasses($classes, $newClasses);

        $this->processConfigFile($classes);
    }

    /**
     * {@inheritdoc}
     */
    public function uninstall(Plugin $plugin): void
    {
        $classes = $this->getExistingClasses();
        $classes = $this->removeClasses($classes, $plugin->getClasses());

        $this->processConfigFile($classes);
    }

    /**
     * @return array<string, string[]>
     */
    protected function getExistingClasses(): array
    {
        $pluginClassesFile = $this->pathResolver->resolve('%config%/plugins/classes.yml');

        return file_exists($pluginClassesFile) ? Yaml::parseFile($pluginClassesFile) : [];
    }

    /**
     * @param array<string, string[]> $existingClasses
     * @param array<string, string[]> $pluginClasses
     *
     * @return array<string, string[]>
     */
    protected function addClasses(array $existingClasses, array $pluginClasses): array
    {
        foreach ($pluginClasses as $class => $environments) {
            foreach ($environments as $environment) {
                $values = $existingClasses[$environment] ?? [];
                $newClass = $this->prepareClass($class);

                if (!in_array($newClass, $values, true)) {
                    $values[] = $newClass;
                }

                $existingClasses[$environment] = array_values($values);
            }
        }

        return $existingClasses;
    }

    /**
     * @param array<string, string[]> $existingClasses
     * @param array<string, string[]> $pluginClasses
     *
     * @return array<string, string[]>
     */
    protected function removeClasses(array $existingClasses, array $pluginClasses): array
    {
        foreach ($pluginClasses as $class => $environments) {
            foreach ($environments as $environment) {
                $values = $existingClasses[$environment] ?? [];
                $existingClasses[$environment] = array_values(
                    array_diff($values, [$this->prepareClass($class)])
                );

                if (empty($existingClasses[$environment])) {
                    unset($existingClasses[$environment]);
                }
            }
        }

        return $existingClasses;
    }

    /**
     * @param string $class
     *
     * @return string
     */
    protected function prepareClass(string $class): string
    {
        return trim($class, '\\');
    }

    /**
     * @param array<string, string[]> $classes
     *
     * @return void
     */
    protected function processConfigFile(array $classes): void
    {
        $pluginConfigDir = $this->pathResolver->resolve('%config%/plugins');
        $pluginClassesFile = $pluginConfigDir . '/classes.yml';

        if (empty($classes)) {
            File::delete($pluginClassesFile);

            return;
        }

        if (!is_dir($pluginConfigDir) && !File::createDirectory($pluginConfigDir)) {
            $this->writeWarning("Could not create directory $pluginConfigDir");
        }

        $header = <<<EOF
# This file is auto-generated by ZAPHYR Plugin Installer.
# Do not edit this file directly as it will be overwritten
# on the next plugin installation or update.
EOF;


        if (!file_put_contents($pluginClassesFile, $header . "\n\n" . Yaml::dump($classes))) {
            $this->writeWarning("Could not write to file $pluginClassesFile");
        }
    }
}
